### ISSUE TITLE
Addition: Add database prefix option

### ISSUE THREAD

**Issue by Malachiel87** [BattlePlugins/BattleTracker#11]
I would like to see a option for add database prefix, since we use the same database and i have to create a new one  for use battletracker on other servers :)

**Comment by Europia79** [comment]
Can you elaborate ? I'm not sure I fully understand.

For `plugins/BattleArena/competitions/*.yml`, You can change the table name. Is this not sufficient for your use-case scenario ?

You can use any of these nodes to change the table name:

``` yaml
Arena:
  database: arena #3
  dbTableName: arena # 4
  tracking:
    database: arena # 1
    dbTableName: arena #2
```

The pound `#` symbol is yaml for comment and it identifies the node order that BattleArena checks.

If BattleArena is creating a yaml section, it'll put the value under `tracking.dbTableName`

Looking at the database, here are some example tables inside:

```
bt_Demolition_overall
bt_Demolition_tally
bt_Demolition_versus
```

So... As you can see, you can customize the table name. But I don't understand why you want to change the prefix ? I'm curious.

I think Alkarin designed it that way because a lot of servers are known to use just ONE database... So the 'bt_' prefix prevents conflicts between two plugins that both want a table with the same name.

Example: `PluginA` wants a table for `arena_overall` and `PluginB` also wants a table called `arena_overall`. Solution ? Prefix the table with the plugin prefix: In this case, **bt_** for BattleTracker.

**Comment by Europia79** [comment]
If i'm understand you correctly, you could edit the arena configuration file on each server and attach whatever prefix you wanted to the `dbTableName:` node.

Example server1:

``` yaml
Arena:
  tracking:
    dbTableName: server1_arena
```

server2:

``` yaml
Arena:
  tracking:
    dbTableName: server2_arena
```

The tables in your database would be:

```
bt_server1_arena_overall
bt_server1_arena_tally
bt_server1_arena_versus
bt_server2_arena_overall
bt_server2_arena_tally
bt_server2_arena_versus
```

Is this a solution for your problem ? Or no ?
